#!/system/bin/sh
#
# Copyright (C) 2015 The Android One OpenSource Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# By karon
PRELOAD_DEST=/data/app
PRELOAD_FLAG=/data/.AoidOneAPP
PRELOAD_SOURCE=/system/third-app
  
if [ ! -d ${PRELOAD_DEST} ]  
then  
    mkdir -p ${PRELOAD_DEST}  
fi  
  
if [ ! -f ${PRELOAD_FLAG} ]  
then  
    files=$(ls ${PRELOAD_SOURCE}/)  
    for i in ${files};do  
        cat  ${PRELOAD_SOURCE}/${i} > ${PRELOAD_DEST}/${i}  
    done  
    echo "true" > ${PRELOAD_FLAG}  
fi  
